applications:
    app:
        type: 'php:8.2'
        relationships:
            database: 'db:mariadb'
            mongodb: 'mongodb:mongodb'
        build:
            flavor: composer
        web:
            locations:
                '/':
                    root: 'public'
                    passthru: '/index.php'
        mounts:
            '/var/cache': { source: 'local', source_path: 'cache' }
            '/var/log': { source: 'local', source_path: 'log' }
        hooks:
            build: |
                php bin/console assets:install public
            deploy: |
                php bin/console doctrine:migrations:migrate --no-interaction

services:
    db:
        type: 'mariadb:10.6'
    mongodb:
        type: 'mongodb:6.0'

routes:
    "https://api.main.{default}/":
        type: upstream
        upstream: "app:http"
    "https://{all}/":
        type: redirect
        to: "https://api.main.{default}/"
