applications:
    app:
        type: 'php:8.2'
        relationships:
            database: 'db:mariadb'
            mongodb: 'mongodb:mongodb'
        build:
            flavor: composer
        web:
            locations:
                '/':
                    root: 'public'
                    passthru: '/index.php'
        disk: 512
        mounts:
            '/var/cache': { source: 'local', source_path: 'cache' }
            '/var/log': { source: 'local', source_path: 'log' }
        hooks:
            build: |
                php bin/console assets:install public
            deploy: |
                php bin/console doctrine:migrations:migrate --no-interaction

services:
    db:
        type: mariadb
        version: '10.6'
        disk: 512
    mongodb:
        type: mongodb
        version: '6.0'
        disk: 512

routes:
    # La route principale qui pointe vers votre application Symfony
    "https://api.main.{default}/":
        type: upstream
        upstream: "app:http" # <-- CORRIGÉ : On utilise le nom de l'application 'app'

    # La route qui redirige tout le trafic vers la route principale
    "https://{all}/":
        type: redirect
        to: "https://api.main.{default}/" # <-- CORRIGÉ : La clé est 'to'
